<?php namespace JF;
/**

Copyright 2019 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-320d9e
Date:    2019-03-28 09:04:37
Version: v3.0.2
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-320d9e",
    "email": {
        "to": "zakiyamin96@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "Upload MOD Minecraft",
        "template": "You receive an email from {sender.fullname}.\n\nThe web form data:\n{dataTable}\n\nReference ID: {AutoID}\nIP: {IP}\nDate: {Date}\nTime: {Time}\nWebsite: {HTTP_HOST}\nReferer: {HTTP_REFERER}\n",
        "sendmail_from": "zakiyamin96@gmail.com",
        "skipEmptyFields": false,
        "fromName": "Exza Apriano"
    },
    "admin": {
        "users": "admin:30952",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Nama MOD",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-file"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Nama MOD wajib diisi!"
                    }
                },
                "placeholder": "Nama MOD ini"
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Uploader",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-user"
                },
                "placeholder": "Namamu",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Nama kamu wajib diisi!"
                    }
                }
            },
            "id": "f5",
            "cid": "c30"
        },
        {
            "label": "Author",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-user"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Nama Pembuat MOD wajib diisi!"
                    }
                },
                "placeholder": "Nama Pembuat MOD ini"
            },
            "id": "f6",
            "cid": "c35"
        },
        {
            "label": "Deskripsi MOD",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Deskripsi MOD wajib diisi!"
                    }
                },
                "placeholder": "Katakan sesuatu tentang MOD ini, misal replace apa, fungsinya apa, dan lain - lain",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-pencil"
                }
            },
            "id": "f7",
            "cid": "c40"
        },
        {
            "label": "File MOD",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "zip,gz,tar,tar.gz,rar,7z",
                    "maxFileSize": "250000",
                    "fileToLinkSize": "5",
                    "browseLabel": "File MOD klik disini"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "File MOD wasjib untuk diupload!"
                    }
                },
                "mainDescription": "",
                "description": "File harus .rar atau .zip ukuran dibawah 250 MB"
            },
            "id": "f8",
            "cid": "c47"
        },
        {
            "label": "Gambar atau Screenshot",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw",
                    "browseLabel": "Pilih Gambar disini"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Screenshot wajib di upload!"
                    }
                },
                "description": "Sebaiknya gunakan screenshot yang berbau MOD Minecraft, gambar lain yang tidak jelas menyebabkan MOD mu tidak di Publish!"
            },
            "id": "f9",
            "cid": "c52"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Upload MOD",
                "icon": "",
                "checkRequiredFields": "Cek field yang wajib untuk diisi"
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class